import {
  eventRulesetSchema,
  type EventDefinition,
  type EventRuleset,
  type LanguageLevel,
} from '@english-pet/contracts'

const allLevels: LanguageLevel[] = ['L1', 'L2', 'L3', 'L4']
const adultLevels: LanguageLevel[] = ['L2', 'L3', 'L4']

function line(id: string, text: string, levels = allLevels) {
  return { id, text, levels }
}

function reply(id: string, text: string) {
  return { id, text, editable: true as const }
}

const sharedBoundaries = [
  'Never punish mistakes, refusal, pausing, absence, or choosing a shorter path.',
  'Do not persist raw audio, uncertain ASR text, inferred sensitive traits, or a misunderstood meaning.',
  'Only declared outcomes may write world state; the model cannot invent rewards, inventory, locations, or relationship changes.',
  'Life, language, and relationship memories are proposals until the user explicitly confirms them.',
]

const events: EventDefinition[] = [
  {
    id: 'morrow_letter_v1',
    version: '1.0.0',
    title: 'The letter with two meanings',
    titleZh: 'Morrow 收到一封看不懂的来信',
    summary:
      'The user helps Morrow interpret a short letter, resolve the two meanings of “leave,” and decide whether to reply now or observe the road first.',
    estimatedMinutes: { min: 3, max: 5 },
    trigger: {
      requiredCompletedEventIds: ['first_day_v1'],
      requiredWorldState: [
        { key: 'first_day_status', operator: 'equals', value: 'completed' },
      ],
      allowedRelationshipStages: ['NEW', 'FAMILIAR', 'TRUSTED', 'CLOSE'],
      repeatPolicy: 'once',
      cooldownHours: null,
      maxConcurrentInstances: 1,
    },
    morrowGoal:
      'Understand the practical request in the letter and choose a response without pretending certainty.',
    targetSkills: ['gist', 'interpretation', 'uncertainty'],
    keyExpressions: [
      'I think it means…',
      'It might mean…',
      "I'm not sure about…",
    ],
    states: [
      {
        id: 'lt01_open',
        phase: 'opening',
        userTask: 'Choose whether to open the letter now or pause the event.',
        lines: [
          line(
            'lt_open',
            'A letter arrived. I understand every word, which is not the same as understanding the letter.',
          ),
        ],
        acceptedInputModes: ['choice'],
        referenceReplies: [],
        recoverable: true,
        checkpoint: true,
      },
      {
        id: 'lt02_gist',
        phase: 'input',
        userTask: 'Explain what the writer wants Morrow to do.',
        lines: [
          line(
            'lt_letter',
            'Keep the light near the window. When the road sounds empty, leave a small sign at the door.',
          ),
          line('lt_gist_question', 'What do you think the writer wants me to do?'),
        ],
        acceptedInputModes: ['text', 'voice', 'reference_reply'],
        referenceReplies: [
          reply(
            'lt_gist_reply',
            'I think it means: keep the light on and leave a sign by the door.',
          ),
          reply(
            'lt_uncertain_reply',
            "I'm not sure about “leave.” It may mean “put something there.”",
          ),
        ],
        recoverable: true,
        checkpoint: true,
      },
      {
        id: 'lt03_confirm',
        phase: 'understanding',
        userTask: 'Confirm or correct Morrow’s paraphrase.',
        lines: [
          line(
            'lt_confirm_line',
            'Let me make sure I understood. Is that what you think the letter means?',
          ),
        ],
        acceptedInputModes: ['choice', 'text', 'voice'],
        referenceReplies: [],
        recoverable: true,
        checkpoint: true,
      },
      {
        id: 'lt04_reply',
        phase: 'choice',
        userTask: 'Choose whether to reply now or observe the road first.',
        lines: [
          line(
            'lt_reply_question',
            'Should I answer now, or wait until we know what the road sounds like?',
          ),
        ],
        acceptedInputModes: ['choice', 'text', 'voice', 'reference_reply'],
        referenceReplies: [
          reply('lt_reply_now', "Let's answer now and say we will leave a sign."),
          reply('lt_observe_first', "Let's listen to the road before we answer."),
        ],
        recoverable: true,
        checkpoint: true,
      },
      {
        id: 'lt05_result',
        phase: 'result',
        userTask: 'Review the result and finish the event.',
        lines: [
          line(
            'lt_result_line',
            'Good. The letter is no longer only a collection of words.',
            adultLevels,
          ),
          line('lt_result_simple', 'Now we know what to do.', ['L1']),
        ],
        acceptedInputModes: ['continue'],
        referenceReplies: [],
        recoverable: true,
        checkpoint: true,
      },
    ],
    transitions: [
      { from: 'lt01_open', to: 'lt02_gist', on: 'continue', guard: 'The user starts the event.' },
      { from: 'lt01_open', to: 'lt01_open', on: 'user_declines', guard: 'Pause without changing the confirmed state.' },
      { from: 'lt02_gist', to: 'lt03_confirm', on: 'meaning_understood', guard: 'At least one required action is understood.' },
      { from: 'lt02_gist', to: 'lt03_confirm', on: 'meaning_ambiguous', guard: 'The meaning of “leave” needs confirmation.' },
      { from: 'lt03_confirm', to: 'lt04_reply', on: 'choice_confirmed', guard: 'The user confirms the paraphrase.' },
      { from: 'lt03_confirm', to: 'lt03_confirm', on: 'clarification_resolved', guard: 'Replace the temporary interpretation with the corrected meaning.' },
      { from: 'lt04_reply', to: 'lt05_result', on: 'choice_confirmed', guard: 'The user selects one declared outcome.' },
      { from: 'lt05_result', to: 'completed', on: 'result_committed', guard: 'The outcome write is committed exactly once.' },
    ],
    misunderstanding: {
      trigger: 'The word “leave” is used without distinguishing “go away” from “put something there.”',
      temporaryEffect: 'Morrow briefly imagines leaving the doorway; no world state changes.',
      morrowLine: 'If I leave the door, there will be no one here to read the next letter. That seems inefficient.',
      clarificationPrompt: 'Do you mean “go away,” or “put a sign there”?',
      recoveryStateId: 'lt03_confirm',
      maxClarificationTurns: 2,
      persistMisunderstoodContent: false,
    },
    outcomes: [
      {
        id: 'reply_now',
        label: 'Reply now',
        condition: 'The user chooses to answer the letter now.',
        worldStateWrites: [{ key: 'letter_response', value: 'reply_now' }],
        visibleEffect: 'A short reply is placed by the door.',
        futureHook: 'The note is already ready when Morrow plans the first outing.',
      },
      {
        id: 'observe_first',
        label: 'Observe the road first',
        condition: 'The user chooses to listen to the road before replying.',
        worldStateWrites: [{ key: 'letter_response', value: 'observe_first' }],
        visibleEffect: 'The letter stays near the window while Morrow listens.',
        futureHook: 'The road sound is checked first during the outing event.',
      },
    ],
    memoryProposals: [
      {
        id: 'letter_language_memory',
        kind: 'language',
        when: 'The user uses or explicitly chooses to keep an interpretation phrase.',
        contentTemplate: 'I think it means…',
        requiresUserConfirmation: true,
        skipIfSensitiveOrInferred: true,
      },
      {
        id: 'letter_relationship_memory',
        kind: 'relationship',
        when: 'The event completes.',
        contentTemplate: 'You and Morrow worked out the meaning of the first letter.',
        requiresUserConfirmation: true,
        skipIfSensitiveOrInferred: true,
      },
    ],
    resurfacing: [
      {
        expression: 'I think it means…',
        targetEventIds: ['literal_misunderstanding_v1', 'first_outing_v1'],
        semanticContexts: ['interpreting meaning', 'explaining a condition'],
        mode: 'optional_natural_prompt',
        requiresConfirmedLanguageMemory: true,
        minEventGap: 1,
        cooldownHours: 20,
      },
    ],
    boundaries: sharedBoundaries,
  },
  {
    id: 'room_object_v1',
    version: '1.0.0',
    title: 'One more thing for the room',
    titleZh: 'Morrow 想给房间增加一件物品',
    summary:
      'The user compares three useful room objects, explains a preference, and chooses one valid placement.',
    estimatedMinutes: { min: 3, max: 5 },
    trigger: {
      requiredCompletedEventIds: ['morrow_letter_v1'],
      requiredWorldState: [{ key: 'first_restored_object', operator: 'exists' }],
      allowedRelationshipStages: ['NEW', 'FAMILIAR', 'TRUSTED', 'CLOSE'],
      repeatPolicy: 'once',
      cooldownHours: null,
      maxConcurrentInstances: 1,
    },
    morrowGoal: 'Choose one useful object for the shared room and understand why it fits.',
    targetSkills: ['description', 'comparison', 'preference', 'reason'],
    keyExpressions: ['I’d rather have… because…', 'It would make the room…'],
    states: [
      {
        id: 'ro01_open',
        phase: 'opening',
        userTask: 'Look at the three available objects.',
        lines: [
          line('ro_open', 'The room has light now, but nowhere sensible to sit, store a letter, or make a warm drink.'),
        ],
        acceptedInputModes: ['continue'],
        referenceReplies: [],
        recoverable: true,
        checkpoint: true,
      },
      {
        id: 'ro02_compare',
        phase: 'choice',
        userTask: 'Choose a low chair, narrow shelf, or small kettle and optionally explain why.',
        lines: [line('ro_compare', 'Which one would make this room easier to live in?')],
        acceptedInputModes: ['choice', 'text', 'voice', 'reference_reply'],
        referenceReplies: [
          reply('ro_kettle', 'I’d rather have a small kettle because the room feels cold.'),
          reply('ro_shelf', 'Let’s add a narrow shelf near the door.'),
        ],
        recoverable: true,
        checkpoint: true,
      },
      {
        id: 'ro03_confirm',
        phase: 'understanding',
        userTask: 'Confirm the object and reason.',
        lines: [line('ro_confirm', 'Let me make sure I understood your choice correctly.')],
        acceptedInputModes: ['choice', 'text', 'voice'],
        referenceReplies: [],
        recoverable: true,
        checkpoint: true,
      },
      {
        id: 'ro04_place',
        phase: 'choice',
        userTask: 'Place the object by the window or near the door.',
        lines: [line('ro_place', 'Should it go by the window, or near the door?')],
        acceptedInputModes: ['choice', 'text', 'voice'],
        referenceReplies: [],
        recoverable: true,
        checkpoint: true,
      },
      {
        id: 'ro05_result',
        phase: 'result',
        userTask: 'Review the room change and finish.',
        lines: [line('ro_result', 'The room looks more deliberate now. That is an improvement.')],
        acceptedInputModes: ['continue'],
        referenceReplies: [],
        recoverable: true,
        checkpoint: true,
      },
    ],
    transitions: [
      { from: 'ro01_open', to: 'ro02_compare', on: 'continue', guard: 'The object choices are visible.' },
      { from: 'ro02_compare', to: 'ro03_confirm', on: 'meaning_understood', guard: 'One supported object or use category is identified.' },
      { from: 'ro02_compare', to: 'ro03_confirm', on: 'meaning_ambiguous', guard: 'The object name or use category needs confirmation.' },
      { from: 'ro03_confirm', to: 'ro04_place', on: 'choice_confirmed', guard: 'The selected object is confirmed.' },
      { from: 'ro03_confirm', to: 'ro03_confirm', on: 'clarification_resolved', guard: 'Use only the corrected object.' },
      { from: 'ro04_place', to: 'ro05_result', on: 'choice_confirmed', guard: 'The placement passes deterministic layout rules.' },
      { from: 'ro05_result', to: 'completed', on: 'result_committed', guard: 'Object and location are committed exactly once.' },
    ],
    misunderstanding: {
      trigger: 'ASR confuses “shelf” with “self,” or the object is clear but placement is not.',
      temporaryEffect: 'No object is placed until the user confirms the intended word and location.',
      morrowLine: 'I heard “self,” but the room already contains both of us. Did you mean “shelf”?',
      clarificationPrompt: 'Which object did you mean, and should it be by the window or near the door?',
      recoveryStateId: 'ro03_confirm',
      maxClarificationTurns: 2,
      persistMisunderstoodContent: false,
    },
    outcomes: [
      {
        id: 'chair_added',
        label: 'Add the low chair',
        condition: 'The confirmed object is the low chair.',
        worldStateWrites: [{ key: 'room_added_object', value: 'low_chair' }],
        visibleEffect: 'A low chair appears at the confirmed valid location.',
        futureHook: 'The daily reflection may happen beside the chair.',
      },
      {
        id: 'shelf_added',
        label: 'Add the narrow shelf',
        condition: 'The confirmed object is the narrow shelf.',
        worldStateWrites: [{ key: 'room_added_object', value: 'narrow_shelf' }],
        visibleEffect: 'A narrow shelf appears and holds the letter.',
        futureHook: 'Morrow takes the letter from the shelf before the outing.',
      },
      {
        id: 'kettle_added',
        label: 'Add the small kettle',
        condition: 'The confirmed object is the small kettle.',
        worldStateWrites: [{ key: 'room_added_object', value: 'small_kettle' }],
        visibleEffect: 'A small kettle adds a low, steady sound to the room.',
        futureHook: 'The kettle sound can open the daily reflection.',
      },
    ],
    memoryProposals: [
      {
        id: 'room_life_memory',
        kind: 'life',
        when: 'The user explicitly connects the choice to a real personal preference and opts to save it.',
        contentTemplate: '{{confirmed_personal_preference}}',
        requiresUserConfirmation: true,
        skipIfSensitiveOrInferred: true,
      },
      {
        id: 'room_language_memory',
        kind: 'language',
        when: 'The user uses or chooses to keep a preference-and-reason phrase.',
        contentTemplate: 'I’d rather have… because…',
        requiresUserConfirmation: true,
        skipIfSensitiveOrInferred: true,
      },
      {
        id: 'room_relationship_memory',
        kind: 'relationship',
        when: 'The event completes.',
        contentTemplate: 'You and Morrow chose a {{room_added_object}} for the room.',
        requiresUserConfirmation: true,
        skipIfSensitiveOrInferred: true,
      },
    ],
    resurfacing: [
      {
        expression: 'I’d rather… because…',
        targetEventIds: ['first_outing_v1'],
        semanticContexts: ['comparing options', 'explaining a preference'],
        mode: 'optional_natural_prompt',
        requiresConfirmedLanguageMemory: true,
        minEventGap: 1,
        cooldownHours: 20,
      },
    ],
    boundaries: [
      ...sharedBoundaries,
      'Only low_chair, narrow_shelf, and small_kettle may be written as MVP room objects; free suggestions must map to an authorized use category.',
    ],
  },
  {
    id: 'literal_misunderstanding_v1',
    version: '1.0.0',
    title: 'What I thought you meant',
    titleZh: 'Morrow 误解了用户的一句话',
    summary:
      'Morrow interprets a current, confirmed sentence honestly; a harmless literal ambiguity may be repaired, but the event never forces a mistake.',
    estimatedMinutes: { min: 3, max: 5 },
    trigger: {
      requiredCompletedEventIds: ['room_object_v1'],
      requiredWorldState: [{ key: 'room_added_object', operator: 'exists' }],
      allowedRelationshipStages: ['NEW', 'FAMILIAR', 'TRUSTED', 'CLOSE'],
      repeatPolicy: 'once',
      cooldownHours: null,
      maxConcurrentInstances: 1,
    },
    morrowGoal: 'Understand one simple current plan and let the user repair any harmless literal misunderstanding.',
    targetSkills: ['clarification', 'rephrasing', 'interpretation'],
    keyExpressions: ['What I meant was…', 'I didn’t mean…', 'Let me say it another way.'],
    states: [
      {
        id: 'mm01_open',
        phase: 'opening',
        userTask: 'Share one simple plan, use a neutral example, or decline.',
        lines: [line('mm_open', 'Tell me one simple plan for later today. I want to see whether I understand it the human way, not the island way.')],
        acceptedInputModes: ['text', 'voice', 'reference_reply', 'choice'],
        referenceReplies: [
          reply('mm_plan', 'I need some quiet time after work.'),
          reply('mm_neutral', 'I need some space.'),
        ],
        recoverable: true,
        checkpoint: true,
      },
      {
        id: 'mm02_input',
        phase: 'input',
        userTask: 'Confirm the text that should be interpreted.',
        lines: [line('mm_input', 'I will use only the sentence you confirm here.')],
        acceptedInputModes: ['text', 'voice', 'choice'],
        referenceReplies: [],
        recoverable: true,
        checkpoint: true,
      },
      {
        id: 'mm03_interpret',
        phase: 'understanding',
        userTask: 'Judge whether Morrow understood correctly.',
        lines: [line('mm_interpret', 'This is what I think you mean. Did I understand correctly?')],
        acceptedInputModes: ['choice', 'text', 'voice'],
        referenceReplies: [],
        recoverable: true,
        checkpoint: true,
      },
      {
        id: 'mm04_clarify',
        phase: 'clarification',
        userTask: 'Clarify freely; the target phrase is optional.',
        lines: [line('mm_clarify', 'I may be taking that too literally. What did you mean?')],
        acceptedInputModes: ['text', 'voice', 'reference_reply'],
        referenceReplies: [
          reply('mm_meant', 'What I meant was: I need some quiet time.'),
          reply('mm_another_way', 'I didn’t mean that literally. Let me say it another way.'),
        ],
        recoverable: true,
        checkpoint: true,
      },
      {
        id: 'mm05_shared_meaning',
        phase: 'result',
        userTask: 'Confirm the final shared meaning and finish.',
        lines: [line('mm_result', 'Now the sentence and the meaning are in the same room.')],
        acceptedInputModes: ['choice', 'continue'],
        referenceReplies: [],
        recoverable: true,
        checkpoint: true,
      },
    ],
    transitions: [
      { from: 'mm01_open', to: 'mm02_input', on: 'continue', guard: 'The user shares or selects a confirmed, safe sentence.' },
      { from: 'mm01_open', to: 'mm02_input', on: 'user_declines', guard: 'Use the neutral, non-personal sentence instead.' },
      { from: 'mm02_input', to: 'mm03_interpret', on: 'meaning_understood', guard: 'The sentence is clear; do not manufacture an error.' },
      { from: 'mm02_input', to: 'mm03_interpret', on: 'meaning_ambiguous', guard: 'A high-confidence, harmless literal ambiguity exists.' },
      { from: 'mm03_interpret', to: 'mm05_shared_meaning', on: 'choice_confirmed', guard: 'The first interpretation is correct.' },
      { from: 'mm03_interpret', to: 'mm04_clarify', on: 'meaning_ambiguous', guard: 'The user says the interpretation is not correct.' },
      { from: 'mm04_clarify', to: 'mm05_shared_meaning', on: 'clarification_resolved', guard: 'The corrected meaning is understood and replaces the temporary interpretation.' },
      { from: 'mm05_shared_meaning', to: 'completed', on: 'result_committed', guard: 'The communication result is committed once.' },
    ],
    misunderstanding: {
      trigger: 'A current confirmed sentence has a high-confidence, harmless literal reading, such as “I need some space.”',
      temporaryEffect: 'A temporary sketch may show the literal reading; no room or personal state changes.',
      morrowLine: 'I first pictured an empty corner of the room. You may mean time alone instead.',
      clarificationPrompt: 'Which kind of space did you mean?',
      recoveryStateId: 'mm04_clarify',
      maxClarificationTurns: 2,
      persistMisunderstoodContent: false,
    },
    outcomes: [
      {
        id: 'meaning_confirmed_first_try',
        label: 'Meaning confirmed first try',
        condition: 'Morrow’s first paraphrase is correct.',
        worldStateWrites: [{ key: 'last_communication_result', value: 'confirmed_first_try' }],
        visibleEffect: 'The understanding card shows one confirmed meaning.',
        futureHook: null,
      },
      {
        id: 'meaning_repaired',
        label: 'Meaning repaired',
        condition: 'The user corrects a harmless misunderstanding.',
        worldStateWrites: [{ key: 'last_communication_result', value: 'repaired' }],
        visibleEffect: 'The temporary literal sketch is replaced by the confirmed meaning.',
        futureHook: 'Morrow may reuse the respectful clarification behavior later.',
      },
      {
        id: 'neutral_example_completed',
        label: 'Neutral example completed',
        condition: 'The user chooses not to share a personal plan.',
        worldStateWrites: [{ key: 'last_communication_result', value: 'neutral_example' }],
        visibleEffect: 'The communication repair is completed without personal content.',
        futureHook: null,
      },
    ],
    memoryProposals: [
      {
        id: 'misunderstanding_life_memory',
        kind: 'life',
        when: 'The user explicitly opts to save the confirmed real plan and it is not sensitive.',
        contentTemplate: '{{confirmed_user_plan}}',
        requiresUserConfirmation: true,
        skipIfSensitiveOrInferred: true,
      },
      {
        id: 'misunderstanding_language_memory',
        kind: 'language',
        when: 'The user uses or chooses to keep a clarification phrase.',
        contentTemplate: 'What I meant was…',
        requiresUserConfirmation: true,
        skipIfSensitiveOrInferred: true,
      },
      {
        id: 'misunderstanding_relationship_memory',
        kind: 'relationship',
        when: 'A misunderstanding is repaired without storing the private sentence.',
        contentTemplate: 'You and Morrow repaired a misunderstanding together.',
        requiresUserConfirmation: true,
        skipIfSensitiveOrInferred: true,
      },
    ],
    resurfacing: [
      {
        expression: 'What I meant was…',
        targetEventIds: ['first_outing_v1', 'today_story_v1'],
        semanticContexts: ['correcting a plan', 'repairing a summary'],
        mode: 'optional_natural_prompt',
        requiresConfirmedLanguageMemory: true,
        minEventGap: 1,
        cooldownHours: 20,
      },
    ],
    boundaries: [
      ...sharedBoundaries,
      'Use only the sentence confirmed in this event; never mine old messages for an embarrassing or sensitive misunderstanding.',
      'If the sentence is clear, paraphrase honestly and do not manufacture an error.',
    ],
  },
  {
    id: 'first_outing_v1',
    version: '1.0.0',
    title: 'The road beyond the window',
    titleZh: 'Morrow 准备第一次外出',
    summary:
      'The user notices a deterministic road condition, chooses when to walk to the mailbox, and confirms an if–then plan.',
    estimatedMinutes: { min: 3, max: 5 },
    trigger: {
      requiredCompletedEventIds: ['literal_misunderstanding_v1'],
      requiredWorldState: [{ key: 'letter_response', operator: 'exists' }],
      allowedRelationshipStages: ['NEW', 'FAMILIAR', 'TRUSTED', 'CLOSE'],
      repeatPolicy: 'once',
      cooldownHours: null,
      maxConcurrentInstances: 1,
    },
    morrowGoal: 'Choose whether and when to take the short path to the mailbox, with one confirmed condition plan.',
    targetSkills: ['planning', 'condition', 'comparison', 'suggestion', 'reason'],
    keyExpressions: ['If …, we can …', 'I’d rather… because…', 'We should take…'],
    states: [
      {
        id: 'ou01_open',
        phase: 'opening',
        userTask: 'Continue to planning or choose not to go today.',
        lines: [line('ou_open', 'The mailbox is only a short walk away. That is still farther than I have gone here.')],
        acceptedInputModes: ['continue', 'choice'],
        referenceReplies: [],
        recoverable: true,
        checkpoint: true,
      },
      {
        id: 'ou02_notice',
        phase: 'input',
        userTask: 'Describe one supplied road or light condition.',
        lines: [line('ou_notice', 'Listen to the road and look at the window light. What do you notice?')],
        acceptedInputModes: ['text', 'voice', 'reference_reply'],
        referenceReplies: [
          reply('ou_quiet', 'The road sounds quiet now.'),
          reply('ou_windy', 'It is windy, and the light looks dim.'),
        ],
        recoverable: true,
        checkpoint: true,
      },
      {
        id: 'ou03_plan',
        phase: 'choice',
        userTask: 'Choose now, wait for quiet, or postpone without penalty.',
        lines: [line('ou_plan', 'Should we go now, wait until it is quieter, or leave it for another day?')],
        acceptedInputModes: ['choice', 'text', 'voice', 'reference_reply'],
        referenceReplies: [
          reply('ou_go', 'If the road stays quiet, we can go to the mailbox now.'),
          reply('ou_wait', 'I’d rather wait because the wind is too strong.'),
        ],
        recoverable: true,
        checkpoint: true,
      },
      {
        id: 'ou04_condition',
        phase: 'understanding',
        userTask: 'Confirm the condition and action; using an if-sentence is optional.',
        lines: [line('ou_condition', 'Let me make sure the condition and the plan match.')],
        acceptedInputModes: ['choice', 'text', 'voice'],
        referenceReplies: [],
        recoverable: true,
        checkpoint: true,
      },
      {
        id: 'ou05_result',
        phase: 'result',
        userTask: 'Review the outing result and finish.',
        lines: [line('ou_result', 'A small plan is still a real plan. The road can wait when it needs to.')],
        acceptedInputModes: ['continue'],
        referenceReplies: [],
        recoverable: true,
        checkpoint: true,
      },
    ],
    transitions: [
      { from: 'ou01_open', to: 'ou02_notice', on: 'continue', guard: 'The user wants to consider the outing.' },
      { from: 'ou01_open', to: 'ou05_result', on: 'user_declines', guard: 'Choose postponed_without_penalty without applying a relationship penalty.' },
      { from: 'ou02_notice', to: 'ou03_plan', on: 'meaning_understood', guard: 'At least one supplied environment fact is understood.' },
      { from: 'ou02_notice', to: 'ou02_notice', on: 'meaning_ambiguous', guard: 'Clarify the observed condition without inventing weather.' },
      { from: 'ou03_plan', to: 'ou04_condition', on: 'choice_confirmed', guard: 'One declared timing option is selected.' },
      { from: 'ou04_condition', to: 'ou05_result', on: 'choice_confirmed', guard: 'The condition and action are explicitly confirmed.' },
      { from: 'ou04_condition', to: 'ou04_condition', on: 'clarification_resolved', guard: 'Replace the ambiguous plan with the corrected plan.' },
      { from: 'ou05_result', to: 'completed', on: 'result_committed', guard: 'The outing status is committed exactly once.' },
    ],
    misunderstanding: {
      trigger: 'The transcript or wording does not reliably distinguish “can” from “can’t,” or the condition is attached to the wrong action.',
      temporaryEffect: 'No outing begins and no condition is saved until the user confirms.',
      morrowLine: 'I heard “we can go.” The word “can’t” changes the whole plan.',
      clarificationPrompt: 'Should we go now, or only after it gets quiet?',
      recoveryStateId: 'ou04_condition',
      maxClarificationTurns: 2,
      persistMisunderstoodContent: false,
    },
    outcomes: [
      {
        id: 'went_to_mailbox',
        label: 'Go to the mailbox now',
        condition: 'The user confirms that the supplied condition permits leaving now.',
        worldStateWrites: [{ key: 'first_outing_status', value: 'completed_now' }],
        visibleEffect: 'Morrow takes the short path and returns with a blank sound card.',
        futureHook: 'The next daily reflection can begin after returning to the room.',
      },
      {
        id: 'waited_for_quiet',
        label: 'Wait for quiet',
        condition: 'The user confirms a valid wait condition.',
        worldStateWrites: [{ key: 'first_outing_status', value: 'waiting_condition' }],
        visibleEffect: 'A prepared note remains by the door until the condition is met.',
        futureHook: 'The system checks the supplied road condition before a short completion scene.',
      },
      {
        id: 'postponed_without_penalty',
        label: 'Leave it for another day',
        condition: 'The user postpones or declines the outing.',
        worldStateWrites: [{ key: 'first_outing_status', value: 'postponed' }],
        visibleEffect: 'The plan stays by the door without loss or disappointment.',
        futureHook: 'A future outing may use a new instance; this event is not forced to repeat.',
      },
    ],
    memoryProposals: [
      {
        id: 'outing_life_memory',
        kind: 'life',
        when: 'The user explicitly links the choice to a real preference and opts to save it.',
        contentTemplate: '{{confirmed_outing_preference}}',
        requiresUserConfirmation: true,
        skipIfSensitiveOrInferred: true,
      },
      {
        id: 'outing_language_memory',
        kind: 'language',
        when: 'The user uses or chooses to keep a condition phrase.',
        contentTemplate: 'If …, we can …',
        requiresUserConfirmation: true,
        skipIfSensitiveOrInferred: true,
      },
      {
        id: 'outing_relationship_memory',
        kind: 'relationship',
        when: 'The event completes, including postponement.',
        contentTemplate: 'You and Morrow planned their first walk to the mailbox.',
        requiresUserConfirmation: true,
        skipIfSensitiveOrInferred: true,
      },
    ],
    resurfacing: [
      {
        expression: 'If …, we can …',
        targetEventIds: ['today_story_v1'],
        semanticContexts: ['talking about a plan', 'explaining a condition'],
        mode: 'optional_natural_prompt',
        requiresConfirmedLanguageMemory: true,
        minEventGap: 1,
        cooldownHours: 20,
      },
    ],
    boundaries: [
      ...sharedBoundaries,
      'The MVP outing ends at the mailbox; do not create new maps, shops, characters, danger, or survival needs.',
      'Postponing the outing is a valid completed outcome and cannot reduce relationship state.',
    ],
  },
  {
    id: 'today_story_v1',
    version: '1.0.0',
    title: 'One thing from today',
    titleZh: 'Morrow 询问用户今天发生的事情',
    summary:
      'The user shares one meaningful detail from today, chooses a one-minute or standard path, or completes a non-personal alternative without pressure.',
    estimatedMinutes: { min: 1, max: 5 },
    trigger: {
      requiredCompletedEventIds: ['first_outing_v1'],
      requiredWorldState: [{ key: 'first_outing_status', operator: 'exists' }],
      allowedRelationshipStages: ['NEW', 'FAMILIAR', 'TRUSTED', 'CLOSE'],
      repeatPolicy: 'repeatable',
      cooldownHours: 20,
      maxConcurrentInstances: 1,
    },
    morrowGoal: 'Understand one real event from the user’s day without turning the exchange into a test or forcing disclosure.',
    targetSkills: ['narration', 'sequence', 'reason', 'reflection', 'clarification'],
    keyExpressions: ['The best part was…', 'The hardest part was…', 'What happened was…'],
    states: [
      {
        id: 'td01_open',
        phase: 'opening',
        userTask: 'Choose a standard story, a one-minute story, a room detail, or stop.',
        lines: [line('td_open', 'Tell me one thing from today—the best part, the hardest part, or simply what happened.')],
        acceptedInputModes: ['choice', 'text', 'voice', 'reference_reply'],
        referenceReplies: [
          reply('td_best', 'The best part was having lunch with a friend.'),
          reply('td_hardest', 'The hardest part was a long meeting at work.'),
        ],
        recoverable: true,
        checkpoint: true,
      },
      {
        id: 'td02_story',
        phase: 'input',
        userTask: 'Share one event or one non-personal room detail.',
        lines: [line('td_story', 'One clear detail is enough.')],
        acceptedInputModes: ['text', 'voice', 'reference_reply'],
        referenceReplies: [
          reply('td_happened', 'What happened was…'),
          reply('td_room', 'The room sounds quiet except for the kettle.'),
        ],
        recoverable: true,
        checkpoint: true,
      },
      {
        id: 'td03_detail',
        phase: 'clarification',
        userTask: 'Answer one relevant follow-up or choose to stop adding details.',
        lines: [line('td_detail', 'Tell me one small detail, or we can leave it there.')],
        acceptedInputModes: ['text', 'voice', 'choice'],
        referenceReplies: [],
        recoverable: true,
        checkpoint: true,
      },
      {
        id: 'td04_understanding',
        phase: 'understanding',
        userTask: 'Confirm or correct Morrow’s short summary.',
        lines: [line('td_understanding', 'Let me make sure I understood your day correctly.')],
        acceptedInputModes: ['choice', 'text', 'voice', 'reference_reply'],
        referenceReplies: [reply('td_correction', 'What I meant was…')],
        recoverable: true,
        checkpoint: true,
      },
      {
        id: 'td05_close',
        phase: 'closing',
        userTask: 'Review feedback and memory proposals, then finish.',
        lines: [line('td_close', 'That is enough for today. We can leave the rest of the day outside the room.')],
        acceptedInputModes: ['continue', 'choice'],
        referenceReplies: [],
        recoverable: true,
        checkpoint: true,
      },
    ],
    transitions: [
      { from: 'td01_open', to: 'td02_story', on: 'continue', guard: 'The user chooses a standard, quick, or room-detail path.' },
      { from: 'td01_open', to: 'td05_close', on: 'user_declines', guard: 'Complete without personal content or a penalty.' },
      { from: 'td02_story', to: 'td03_detail', on: 'meaning_understood', guard: 'The standard path has one understandable event and time remains.' },
      { from: 'td02_story', to: 'td04_understanding', on: 'choice_confirmed', guard: 'The one-minute or room-detail path skips follow-up.' },
      { from: 'td02_story', to: 'td02_story', on: 'meaning_ambiguous', guard: 'Ask one targeted clarification or offer a reference reply.' },
      { from: 'td03_detail', to: 'td04_understanding', on: 'meaning_understood', guard: 'One detail is understood.' },
      { from: 'td03_detail', to: 'td04_understanding', on: 'user_declines', guard: 'The user chooses “That’s enough.”' },
      { from: 'td04_understanding', to: 'td05_close', on: 'choice_confirmed', guard: 'The user confirms the summary.' },
      { from: 'td04_understanding', to: 'td04_understanding', on: 'clarification_resolved', guard: 'The corrected summary replaces the wrong one.' },
      { from: 'td05_close', to: 'completed', on: 'result_committed', guard: 'The declared result and reviewed memories are committed once.' },
    ],
    misunderstanding: {
      trigger: 'Time order, subject, or a key event in the user’s confirmed story is ambiguous.',
      temporaryEffect: 'The summary remains a draft and is excluded from memories and the journal.',
      morrowLine: 'I may have put the pieces in the wrong order.',
      clarificationPrompt: 'Did that happen before the meeting, or after it?',
      recoveryStateId: 'td04_understanding',
      maxClarificationTurns: 2,
      persistMisunderstoodContent: false,
    },
    outcomes: [
      {
        id: 'story_shared',
        label: 'Share one story',
        condition: 'The user confirms one main meaning in the standard path.',
        worldStateWrites: [{ key: 'last_today_story_result', value: 'story_shared' }],
        visibleEffect: 'A short, confirmed journal entry is created.',
        futureHook: 'A confirmed relevant memory may be referenced naturally later.',
      },
      {
        id: 'quick_story_shared',
        label: 'Share a one-minute story',
        condition: 'The user chooses the quick path and confirms one meaning.',
        worldStateWrites: [{ key: 'last_today_story_result', value: 'quick_story_shared' }],
        visibleEffect: 'A shorter journal entry is created with the same relationship value.',
        futureHook: null,
      },
      {
        id: 'room_detail_shared',
        label: 'Describe a room detail',
        condition: 'The user chooses a non-personal alternative.',
        worldStateWrites: [{ key: 'last_today_story_result', value: 'room_detail_shared' }],
        visibleEffect: 'The shared room detail is recorded without personal life content.',
        futureHook: null,
      },
      {
        id: 'closed_without_sharing',
        label: 'Close without sharing',
        condition: 'The user declines both personal and room-detail paths.',
        worldStateWrites: [{ key: 'last_today_story_result', value: 'closed_without_sharing' }],
        visibleEffect: 'The conversation closes calmly with no personal summary.',
        futureHook: 'The next event does not ask why the user declined.',
      },
    ],
    memoryProposals: [
      {
        id: 'today_life_memory',
        kind: 'life',
        when: 'The user confirms a specific non-sensitive fact and chooses to save it.',
        contentTemplate: '{{confirmed_today_fact}}',
        requiresUserConfirmation: true,
        skipIfSensitiveOrInferred: true,
      },
      {
        id: 'today_language_memory',
        kind: 'language',
        when: 'The user uses or chooses to keep a reflection phrase.',
        contentTemplate: 'The best part was… / The hardest part was…',
        requiresUserConfirmation: true,
        skipIfSensitiveOrInferred: true,
      },
      {
        id: 'today_relationship_memory',
        kind: 'relationship',
        when: 'The user shares and confirms one detail; skip for closed_without_sharing.',
        contentTemplate: 'You told Morrow one thing from your day.',
        requiresUserConfirmation: true,
        skipIfSensitiveOrInferred: true,
      },
    ],
    resurfacing: [
      {
        expression: 'The best part was… / The hardest part was…',
        targetEventIds: ['today_story_v1'],
        semanticContexts: ['reflecting on a similar day', 'choosing one important detail'],
        mode: 'optional_natural_prompt',
        requiresConfirmedLanguageMemory: true,
        minEventGap: 1,
        cooldownHours: 44,
      },
    ],
    boundaries: [
      ...sharedBoundaries,
      'If the user does not want to discuss the day, accept it immediately and offer only a room-detail path or a clean stop.',
      'Do not infer a lasting emotion, diagnosis, workplace identity, or relationship from one daily story.',
    ],
  },
]

const rulesetCandidate = {
  id: 'events-v1.0.0',
  version: '1.0.0',
  personaVersion: 'morrow-1.0',
  promptVersion: 'morrow-system-1.0',
  outputSchemaVersion: 'morrow-reply-1.0',
  events,
}

export const eventsV1: EventRuleset = eventRulesetSchema.parse(rulesetCandidate)

export function getEventDefinition(eventId: string): EventDefinition | undefined {
  return eventsV1.events.find((event) => event.id === eventId)
}
